/* SPDX-License-Identifier: GPL-3.0-only */
/**
 * IR0 Kernel — Core system software
 * Copyright (C) 2026  Iván Rodriguez
 *
 * File: syscall_id.h
 * Description: Architecture-neutral syscall identities and ABI decoder facade.
 */

#ifndef IR0_SYSCALL_ID_H
#define IR0_SYSCALL_ID_H

#include <stdint.h>

enum ir0_syscall_id
{
	IR0_SYSCALL_UNKNOWN = 0,
	IR0_SYSCALL_READ,
	IR0_SYSCALL_WRITE,
	IR0_SYSCALL_OPENAT,
	IR0_SYSCALL_CLOSE,
	IR0_SYSCALL_FACCESSAT,
	IR0_SYSCALL_NEWFSTATAT,
	IR0_SYSCALL_FSTAT,
	IR0_SYSCALL_GETDENTS64,
	IR0_SYSCALL_DUP,
	IR0_SYSCALL_DUP3,
	IR0_SYSCALL_PIPE2,
	IR0_SYSCALL_IOCTL,
	IR0_SYSCALL_FCNTL,
	IR0_SYSCALL_CLONE,
	IR0_SYSCALL_FORK,
	IR0_SYSCALL_EXECVE,
	IR0_SYSCALL_WAIT4,
	IR0_SYSCALL_EXIT,
	IR0_SYSCALL_EXIT_GROUP,
	IR0_SYSCALL_NANOSLEEP,
	IR0_SYSCALL_CLOCK_GETTIME,
	IR0_SYSCALL_CLOCK_GETRES,
	IR0_SYSCALL_CLOCK_NANOSLEEP,
	IR0_SYSCALL_GETTIMEOFDAY,
	IR0_SYSCALL_GETPID,
	IR0_SYSCALL_GETPPID,
	IR0_SYSCALL_GETTID,
	IR0_SYSCALL_GETUID,
	IR0_SYSCALL_GETEUID,
	IR0_SYSCALL_GETGID,
	IR0_SYSCALL_GETEGID,
	IR0_SYSCALL_SET_TID_ADDRESS,
	IR0_SYSCALL_SET_ROBUST_LIST,
	IR0_SYSCALL_RT_SIGACTION,
	IR0_SYSCALL_RT_SIGPROCMASK,
	IR0_SYSCALL_RT_SIGRETURN,
	IR0_SYSCALL_UNAME,
	IR0_SYSCALL_PRCTL,
	IR0_SYSCALL_GETCWD,
	IR0_SYSCALL_CHDIR,
	IR0_SYSCALL_BRK,
	IR0_SYSCALL_MUNMAP,
	IR0_SYSCALL_MMAP,
	IR0_SYSCALL_MPROTECT,
	IR0_SYSCALL_PPOLL,
	IR0_SYSCALL_PRLIMIT64,
	IR0_SYSCALL_GETRANDOM,
	IR0_SYSCALL_RSEQ,
	IR0_SYSCALL_COUNT
};

/** Translate the active userspace ABI number into an IR0 semantic identity. */
enum ir0_syscall_id syscall_decode_number(uint64_t abi_number);

#endif
