# IR0 KERNEL MAKEFILE - x86-64 ONLY

KERNEL_ROOT := $(CURDIR)

# Default architecture (can be overridden with arch=x86-64 only)
ARCH ?= x86-64

CFLAGS_TARGET := -DIR0_DESKTOP


IR0_VERSION_MAJOR := 0
IR0_VERSION_MINOR := 0
IR0_VERSION_PATCH := 1
IR0_VERSION_SUFFIX := -pre-rc3
IR0_VERSION_STRING := $(IR0_VERSION_MAJOR).$(IR0_VERSION_MINOR).$(IR0_VERSION_PATCH)$(IR0_VERSION_SUFFIX)

# Build information 

IR0_BUILD_DATE := $(shell LC_TIME=C date +"%b %d %Y")
IR0_BUILD_TIME := $(shell date +"%H:%M:%S")
IR0_BUILD_USER := $(shell whoami 2>/dev/null || echo "unknown")
IR0_BUILD_HOST := $(shell hostname 2>/dev/null || echo "localhost")
IR0_BUILD_CC := $(shell $(CC) --version 2>/dev/null | head -n1 | cut -d' ' -f1-3 || echo "gcc unknown")
# Build number - auto-increment on each build
IR0_BUILD_NUMBER := $(shell [ -f .build_number ] && cat .build_number || echo "1")
# Increment build number for next build (only if building kernel target)
-include .build_number_inc

# Load .config if it exists (generated by menuconfig).
# When .config is absent every CONFIG_* variable is empty and
# the ifneq(…,n) guards below default all subsystems to ON.
-include .config

# Tooling defaults from menuconfig (.config)
CONFIG_TOOL_AUTO_RUN_DEPTEST ?= n
CONFIG_TOOL_DEFAULT_DISK_FS ?= 0
CONFIG_TOOL_DEFAULT_DISK_SIZE_MB ?= 200
CONFIG_TOOL_UNIBUILD_DEFAULT_FILES ?=
CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE ?=

ifeq ($(CONFIG_TOOL_DEFAULT_DISK_FS),1)
TOOL_DEFAULT_DISK_FS_NAME := fat32
else ifeq ($(CONFIG_TOOL_DEFAULT_DISK_FS),2)
TOOL_DEFAULT_DISK_FS_NAME := ext4
else
TOOL_DEFAULT_DISK_FS_NAME := minix
endif

# COMPILER CONFIGURATION (x86-64)

# Build tools
CC = gcc
LD = ld
ASM = nasm
NASM = nasm
QEMU = qemu-system-x86_64
PYTHON = python3

# Flags
CFLAGS = -m64 -ffreestanding -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -nostdlib -g -Wall -Wextra -fno-stack-protector -fno-builtin
NASMFLAGS = -f elf64

# Directories
BUILD_DIR = build
ISO_DIR = iso

# Targets
all: kernel-x64.iso

menuconfig:
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py

menuconfig-en:
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --set TOOL_MENUCONFIG_LANG=en >/dev/null
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py

menuconfig-es:
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --set TOOL_MENUCONFIG_LANG=es >/dev/null
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py

defconfig:
	@cp $(KERNEL_ROOT)/setup/defconfig $(KERNEL_ROOT)/.config
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --sync
	@echo "✓ Default configuration written to .config"
	@echo "  Run 'make menuconfig' to customize, or 'make ir0' to build."

CFLAGS += $(CFLAGS_TARGET)

# Include paths
CFLAGS += -I$(KERNEL_ROOT)
CFLAGS += -I$(KERNEL_ROOT)/includes
CFLAGS += -I$(KERNEL_ROOT)/includes/ir0
CFLAGS += -I$(KERNEL_ROOT)/mm
CFLAGS += -I$(KERNEL_ROOT)/arch/common
CFLAGS += -I$(KERNEL_ROOT)/kernel
CFLAGS += -I$(KERNEL_ROOT)/drivers
CFLAGS += -I$(KERNEL_ROOT)/fs
CFLAGS += -I$(KERNEL_ROOT)/interrupt
CFLAGS += -I$(KERNEL_ROOT)/include/generated
CFLAGS += -MMD -MP

# C++ compile flags (freestanding kernel); matches %.o: %.cpp rule
CXX_KERNEL_FLAGS = -m64 -ffreestanding -fno-exceptions -fno-rtti -fno-threadsafe-statics \
	-mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2 \
	-nostdlib -g -Wall -Wextra -fno-stack-protector -fno-builtin \
	-I$(KERNEL_ROOT)/cpp/include
CXXFLAGS_COMPILE = $(CXX_KERNEL_FLAGS) $(CFLAGS)

# Assembler and linker flags
ASMFLAGS = -f elf64
LDFLAGS = -m elf_x86_64 -T arch/x86-64/linker.ld -Map=kernel-x64.map


# CONFIGURACIÓN QEMU (ABSTRACCIÓN)

# Comandos QEMU por arquitectura
QEMU_64_CMD = qemu-system-x86_64

# Configuración QEMU básica
QEMU_MEMORY = 512M
QEMU_FLAGS = -no-reboot -no-shutdown
QEMU_TIMEOUT = 30

# Modos de display
QEMU_DISPLAY_GTK = -display gtk
QEMU_DISPLAY_SDL = -display sdl2
QEMU_DISPLAY_NONE = -display none
QEMU_NGRAPHIC = -nographic

# Configuración por defecto
QEMU_DISPLAY = $(QEMU_DISPLAY_GTK)
QEMU_SERIAL = -serial stdio
QEMU_TEST_DISPLAY = $(QEMU_DISPLAY_NONE)  # Para pruebas automáticas

# Opciones de debugging y logging
QEMU_DEBUG_INT = -d int,cpu_reset
QEMU_DEBUG_EXEC = -d exec
QEMU_DEBUG_GUEST = -d guest_errors
QEMU_DEBUG_PAGE = -d page
QEMU_DEBUG_ALL = -d int,cpu_reset,exec,guest_errors,page
QEMU_LOG_FILE = -D qemu_debug.log

# Hardware soportado por IR0 Kernel
# Network: RTL8139
# User-mode networking: permite UDP pero ICMP saliente está limitado
# Para mejor soporte de ping, usar TAP networking (ver QEMU_NET_RTL8139_TAP)
QEMU_NET_RTL8139 = -netdev user,id=net0 -device rtl8139,netdev=net0

# TAP networking: Permite ping bidireccional (requiere permisos root y bridge configurado)
# Uso: 1) Crear bridge: sudo ip link add br0 type bridge
#      2) Agregar interfaz física: sudo ip link set eth0 master br0 (o wlan0)
#      3) Crear TAP: sudo ip tuntap add tap0 mode tap
#      4) Agregar TAP al bridge: sudo ip link set tap0 master br0
#      5) Activar interfaces: sudo ip link set br0 up && sudo ip link set tap0 up
#      6) Usar: make run-tap (o cambiar QEMU_NET_ALL a usar QEMU_NET_RTL8139_TAP)
QEMU_NET_RTL8139_TAP = -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device rtl8139,netdev=net0
ifneq ($(CONFIG_ENABLE_NETWORKING),n)
QEMU_NET_ALL = $(QEMU_NET_RTL8139)
else
QEMU_NET_ALL =
endif

# Audio: Sound Blaster 16 y Adlib OPL2 (sintaxis moderna QEMU)
QEMU_AUDIO_SB16 = -device sb16
QEMU_AUDIO_ADLIB = -device adlib
ifneq ($(CONFIG_ENABLE_SOUND),n)
QEMU_AUDIO_ALL = $(QEMU_AUDIO_SB16) $(QEMU_AUDIO_ADLIB)
else
QEMU_AUDIO_ALL =
endif

# Storage: ATA/IDE disk
QEMU_STORAGE_IDE = -drive file=disk.img,format=raw,if=ide,index=0

# Serial: COM1 para debug
QEMU_SERIAL_COM1 = -serial stdio


QEMU_HW_IR0_ALL = $(QEMU_NET_ALL) $(QEMU_AUDIO_ALL) $(QEMU_STORAGE_IDE) $(QEMU_SERIAL_COM1)

QEMU_64_FLAGS = -cdrom

# KERNEL OBJECTS 

KERNEL_OBJS = \
	kernel/main.o \
    kernel/init.o \
    kernel/process.o \
    kernel/task.o \
    kernel/syscalls.o \
    kernel/input_events.o \
    debug_bins/dbgshell.o \
    kernel/elf_loader.o \
    kernel/driver_registry.o \
    kernel/resource_registry.o \
    kernel/ipc.o \
    kernel/net_compat.o \
    kernel/scheduler_api.o \
    kernel/input_backend.o \
    kernel/video_backend.o \
    kernel/console_backend.o \
    debug_bins/debug_bins_registry.o \
    debug_bins/cmd_ls.o \
    debug_bins/cmd_cd.o \
    debug_bins/cmd_pwd.o \
    debug_bins/cmd_cat.o \
    debug_bins/cmd_mkdir.o \
    debug_bins/cmd_rm.o \
    debug_bins/cmd_rmdir.o \
    debug_bins/cmd_touch.o \
    debug_bins/cmd_cp.o \
    debug_bins/cmd_mv.o \
    debug_bins/cmd_ln.o \
    debug_bins/cmd_echo.o \
    debug_bins/cmd_exec.o \
    debug_bins/cmd_sed.o \
    debug_bins/cmd_mount.o \
    debug_bins/cmd_chmod.o \
    debug_bins/cmd_chown.o \
    debug_bins/cmd_ps.o \
    debug_bins/cmd_df.o \
    debug_bins/cmd_dmesg.o \
    debug_bins/cmd_ping.o \
    debug_bins/cmd_uname.o \
    debug_bins/cmd_lsblk.o \
    debug_bins/cmd_lsdrv.o \
    debug_bins/cmd_lsblue.o \
    debug_bins/cmd_bluestart.o \
    debug_bins/cmd_free.o \
    debug_bins/cmd_uptime.o \
    debug_bins/cmd_date.o \
    debug_bins/cmd_lshw.o \
    debug_bins/cmd_blue.o

# debug_bins_registry_test.o: misma fuente que debug_bins_registry.o pero con IR0_KERNEL_TESTS=1
# Evita que make reutilice un .o compilado para tests al hacer make ir0 (y viceversa)
debug_bins/debug_bins_registry_test.o: debug_bins/debug_bins_registry.c
	@echo "  CC      $< (IR0_KERNEL_TESTS=1)"
	@$(CC) $(CFLAGS) -DIR0_KERNEL_TESTS=1 \
		-DIR0_BUILD_DATE_STRING="\"$(IR0_BUILD_DATE)\"" \
		-DIR0_BUILD_TIME_STRING="\"$(IR0_BUILD_TIME)\"" \
		-DIR0_BUILD_USER_STRING="\"$(IR0_BUILD_USER)\"" \
		-DIR0_BUILD_HOST_STRING="\"$(IR0_BUILD_HOST)\"" \
		-DIR0_BUILD_CC_STRING="\"$(IR0_BUILD_CC)\"" \
		-DIR0_BUILD_NUMBER_STRING="\"$(IR0_BUILD_NUMBER)\"" \
		-c $< -o $@

# In-kernel test suite y comando ktest: solo se enlazan en kernel-x64-test.bin (make tests)
KERNEL_TEST_OBJS = debug_bins/debug_bins_registry_test.o \
	debug_bins/cmd_ktest.o \
	kernel/test/test_runner.o \
	kernel/test/test_syscall.o \
	kernel/test/test_procfs.o \
	kernel/test/test_process.o \
	kernel/test/test_resource_registry.o \
	kernel/test/test_allocator.o \
	kernel/test/test_path.o \
	kernel/test/test_string.o

# Scheduler backend selection from menuconfig
ifeq ($(CONFIG_SCHEDULER_POLICY),1)
SCHED_OBJS = kernel/cfs_sched.o
else ifeq ($(CONFIG_SCHEDULER_POLICY),2)
SCHED_OBJS = kernel/priority_sched.o
else
SCHED_OBJS =
endif
KERNEL_OBJS += kernel/rr_sched.o $(SCHED_OBJS)

MEMORY_OBJS = \
	mm/allocator.o \
	mm/paging.o \
	mm/pmm.o \
	mm/kmem.o

LIB_OBJS = \
    includes/ir0/vga.o \
    includes/ir0/logging.o \
    includes/ir0/oops.o \
    includes/ir0/signals.o \
    includes/ir0/pipe.o \
    includes/ir0/copy_user.o \
    includes/string.o

INTERRUPT_OBJS = \
    interrupt/arch/idt.o \
    interrupt/arch/pic.o \
    interrupt/arch/isr_handlers.o \
    interrupt/arch/keyboard.o \
    interrupt/arch/x86-64/isr_stubs_64.o

DRIVER_OBJS = \
    drivers/driver_bootstrap.o \
    drivers/IO/ps2.o \
    drivers/serial/serial.o \
    drivers/timer/pit/pit.o \
    drivers/timer/clock_system.o \
    drivers/timer/rtc/rtc.o \
    drivers/timer/hpet/hpet.o \
    drivers/timer/hpet/find_hpet.o \
    drivers/timer/lapic/lapic.o \
    drivers/storage/block_dev.o \
    drivers/storage/fs_types.o \
	drivers/video/console.o \
	drivers/video/console_font.o \
	drivers/video/typewriter.o \
	drivers/init_drv.o \
	$(MULTILANG_DRIVER_SUPPORT_OBJ)

FS_OBJS = \
    fs/vfs.o \
    fs/path.o \
    fs/chmod.o \
    fs/permissions.o \
    fs/procfs.o \
    fs/devfs.o \
    fs/sysfs.o

ifneq ($(CONFIG_ENABLE_FS_MINIX),n)
FS_OBJS += fs/minix_fs.o
CFLAGS += -DCONFIG_ENABLE_FS_MINIX=1
else
CFLAGS += -DCONFIG_ENABLE_FS_MINIX=0
endif

ifneq ($(CONFIG_ENABLE_FS_TMPFS),n)
FS_OBJS += fs/tmpfs.o
CFLAGS += -DCONFIG_ENABLE_FS_TMPFS=1
else
CFLAGS += -DCONFIG_ENABLE_FS_TMPFS=0
endif

DISK_OBJS = \
    drivers/disk/partition.o

# ============================================
# CONDITIONAL SUBSYSTEM OBJECTS
# ============================================
# Controlled by .config (generated by menuconfig).
# Pattern: ifneq(…,n) makes the subsystem compile when the variable
# is empty (no .config) OR "y", keeping the build backward-compatible.

# Networking (IPv4 stack + RTL8139 NIC driver)
ifneq ($(CONFIG_ENABLE_NETWORKING),n)
NET_OBJS = \
    net/net.o \
    net/arp.o \
    net/ip.o \
    net/icmp.o \
    net/udp.o \
    net/dns.o
NET_DRIVER_OBJS = \
    drivers/net/net_drivers.o \
    drivers/net/rtl8139.o
CFLAGS += -DCONFIG_ENABLE_NETWORKING=1
else
NET_OBJS =
NET_DRIVER_OBJS =
CFLAGS += -DCONFIG_ENABLE_NETWORKING=0
endif

# Sound (Sound Blaster 16 + Adlib OPL2 + ISA DMA)
ifneq ($(CONFIG_ENABLE_SOUND),n)
SOUND_OBJS = \
    drivers/audio/sound_blaster.o \
    drivers/audio/adlib.o \
    drivers/dma/dma.o
CFLAGS += -DCONFIG_ENABLE_SOUND=1
else
SOUND_OBJS =
CFLAGS += -DCONFIG_ENABLE_SOUND=0
endif

# Bluetooth (HCI-UART transport + device manager)
ifneq ($(CONFIG_ENABLE_BLUETOOTH),n)
BLUETOOTH_OBJS = \
    drivers/bluetooth/hci_uart.o \
    drivers/bluetooth/hci_core.o \
    drivers/bluetooth/bt_device.o \
    drivers/bluetooth/bt_sysfs.o \
    drivers/bluetooth/bluetooth_init.o
CFLAGS += -DCONFIG_ENABLE_BLUETOOTH=1
else
BLUETOOTH_OBJS =
CFLAGS += -DCONFIG_ENABLE_BLUETOOTH=0
endif

# PS/2 mouse
ifneq ($(CONFIG_ENABLE_MOUSE),n)
MOUSE_OBJS = drivers/IO/ps2_mouse.o
CFLAGS += -DCONFIG_ENABLE_MOUSE=1
else
MOUSE_OBJS =
CFLAGS += -DCONFIG_ENABLE_MOUSE=0
endif

# PC speaker
ifneq ($(CONFIG_ENABLE_PC_SPEAKER),n)
PC_SPEAKER_OBJS = drivers/IO/pc_speaker.o
CFLAGS += -DCONFIG_ENABLE_PC_SPEAKER=1
else
PC_SPEAKER_OBJS =
CFLAGS += -DCONFIG_ENABLE_PC_SPEAKER=0
endif

# ATA core / block layer
ifneq ($(CONFIG_ENABLE_STORAGE_ATA),n)
STORAGE_ATA_OBJS = \
    drivers/storage/ata.o \
    drivers/storage/ata_helpers.o
CFLAGS += -DCONFIG_ENABLE_STORAGE_ATA=1
else
STORAGE_ATA_OBJS =
CFLAGS += -DCONFIG_ENABLE_STORAGE_ATA=0
endif

ifneq ($(CONFIG_ENABLE_STORAGE_ATA),n)
ifneq ($(CONFIG_ENABLE_STORAGE_ATA_BLOCK),n)
STORAGE_ATA_BLOCK_OBJS = drivers/storage/ata_block.o
CFLAGS += -DCONFIG_ENABLE_STORAGE_ATA_BLOCK=1
else
STORAGE_ATA_BLOCK_OBJS =
CFLAGS += -DCONFIG_ENABLE_STORAGE_ATA_BLOCK=0
endif
else
STORAGE_ATA_BLOCK_OBJS =
CFLAGS += -DCONFIG_ENABLE_STORAGE_ATA_BLOCK=0
endif

# VBE framebuffer (VGA text console is always compiled)
ifneq ($(CONFIG_ENABLE_VBE),n)
VBE_OBJS = drivers/video/vbe.o
CFLAGS += -DCONFIG_ENABLE_VBE=1
else
VBE_OBJS =
CFLAGS += -DCONFIG_ENABLE_VBE=0
endif

# Driver boot init selection flags
ifneq ($(CONFIG_INIT_PS2_CONTROLLER),n)
CFLAGS += -DCONFIG_INIT_PS2_CONTROLLER=1
else
CFLAGS += -DCONFIG_INIT_PS2_CONTROLLER=0
endif
ifneq ($(CONFIG_INIT_PC_SPEAKER),n)
CFLAGS += -DCONFIG_INIT_PC_SPEAKER=1
else
CFLAGS += -DCONFIG_INIT_PC_SPEAKER=0
endif
ifneq ($(CONFIG_INIT_STORAGE_ATA),n)
CFLAGS += -DCONFIG_INIT_STORAGE_ATA=1
else
CFLAGS += -DCONFIG_INIT_STORAGE_ATA=0
endif
ifneq ($(CONFIG_INIT_STORAGE_ATA_BLOCK),n)
CFLAGS += -DCONFIG_INIT_STORAGE_ATA_BLOCK=1
else
CFLAGS += -DCONFIG_INIT_STORAGE_ATA_BLOCK=0
endif
ifneq ($(CONFIG_INIT_SOUND_DRIVERS),n)
CFLAGS += -DCONFIG_INIT_SOUND_DRIVERS=1
else
CFLAGS += -DCONFIG_INIT_SOUND_DRIVERS=0
endif
ifneq ($(CONFIG_INIT_MOUSE_DRIVER),n)
CFLAGS += -DCONFIG_INIT_MOUSE_DRIVER=1
else
CFLAGS += -DCONFIG_INIT_MOUSE_DRIVER=0
endif
ifneq ($(CONFIG_INIT_NETWORK_STACK),n)
CFLAGS += -DCONFIG_INIT_NETWORK_STACK=1
else
CFLAGS += -DCONFIG_INIT_NETWORK_STACK=0
endif
ifneq ($(CONFIG_INIT_BLUETOOTH_DRIVER),n)
CFLAGS += -DCONFIG_INIT_BLUETOOTH_DRIVER=1
else
CFLAGS += -DCONFIG_INIT_BLUETOOTH_DRIVER=0
endif

# Debug flags — only passed when explicitly set to y in .config
ifeq ($(CONFIG_DEBUG_MEMORY_ALLOCATOR),y)
CFLAGS += -DCONFIG_DEBUG_MEMORY_ALLOCATOR=1
else
CFLAGS += -DCONFIG_DEBUG_MEMORY_ALLOCATOR=0
endif
ifeq ($(CONFIG_DEBUG_PMM),y)
CFLAGS += -DCONFIG_DEBUG_PMM=1
else
CFLAGS += -DCONFIG_DEBUG_PMM=0
endif
ifeq ($(CONFIG_DEBUG_PAGING),y)
CFLAGS += -DCONFIG_DEBUG_PAGING=1
else
CFLAGS += -DCONFIG_DEBUG_PAGING=0
endif
ifeq ($(CONFIG_DEBUG_PAGE_FAULTS),y)
CFLAGS += -DCONFIG_DEBUG_PAGE_FAULTS=1
else
CFLAGS += -DCONFIG_DEBUG_PAGE_FAULTS=0
endif
ifeq ($(CONFIG_DEBUG_PROCESS),y)
CFLAGS += -DCONFIG_DEBUG_PROCESS=1
else
CFLAGS += -DCONFIG_DEBUG_PROCESS=0
endif
ifeq ($(CONFIG_DEBUG_SCHEDULER),y)
CFLAGS += -DCONFIG_DEBUG_SCHEDULER=1
else
CFLAGS += -DCONFIG_DEBUG_SCHEDULER=0
endif
ifeq ($(CONFIG_DEBUG_VFS),y)
CFLAGS += -DCONFIG_DEBUG_VFS=1
else
CFLAGS += -DCONFIG_DEBUG_VFS=0
endif
ifeq ($(CONFIG_DEBUG_SYSCALLS),y)
CFLAGS += -DCONFIG_DEBUG_SYSCALLS=1
else
CFLAGS += -DCONFIG_DEBUG_SYSCALLS=0
endif
ifeq ($(CONFIG_DEBUG_KEYBOARD),y)
CFLAGS += -DCONFIG_DEBUG_KEYBOARD=1
else
CFLAGS += -DCONFIG_DEBUG_KEYBOARD=0
endif
ifeq ($(CONFIG_DEBUG_MEMORY_COALESCING),y)
CFLAGS += -DCONFIG_DEBUG_MEMORY_COALESCING=1
else
CFLAGS += -DCONFIG_DEBUG_MEMORY_COALESCING=0
endif
ifeq ($(CONFIG_DEBUG_MEMORY_STATS),y)
CFLAGS += -DCONFIG_DEBUG_MEMORY_STATS=1
else
CFLAGS += -DCONFIG_DEBUG_MEMORY_STATS=0
endif
ifeq ($(CONFIG_DEBUG_FORK),y)
CFLAGS += -DCONFIG_DEBUG_FORK=1
else
CFLAGS += -DCONFIG_DEBUG_FORK=0
endif
ifeq ($(CONFIG_DEBUG_FS_MOUNT),y)
CFLAGS += -DCONFIG_DEBUG_FS_MOUNT=1
else
CFLAGS += -DCONFIG_DEBUG_FS_MOUNT=0
endif
ifeq ($(CONFIG_DEBUG_SYSCALL_PARAMS),y)
CFLAGS += -DCONFIG_DEBUG_SYSCALL_PARAMS=1
else
CFLAGS += -DCONFIG_DEBUG_SYSCALL_PARAMS=0
endif

# Tick rate (PIT frequency)
ifneq ($(CONFIG_TICK_RATE_HZ),)
CFLAGS += -DCONFIG_TICK_RATE_HZ=$(CONFIG_TICK_RATE_HZ)
endif

# Kernel debug shell as PID 1
ifneq ($(CONFIG_KERNEL_DEBUG_SHELL),n)
CFLAGS += -DCONFIG_KERNEL_DEBUG_SHELL=1
else
CFLAGS += -DCONFIG_KERNEL_DEBUG_SHELL=0
endif

ARCH_OBJS = \
    arch/x86-64/sources/arch_x64.o \
    arch/x86-64/sources/gdt.o \
    arch/x86-64/sources/tss_x64.o \
    arch/x86-64/sources/arch_early.o \
    arch/x86-64/sources/user_mode.o \
    arch/x86-64/sources/idt_arch_x64.o \
    arch/x86-64/sources/fault.o \
    arch/x86-64/asm/boot_x64.o \
    arch/x86-64/asm/syscall_entry_64.o \
    arch/common/arch_interface.o \
    kernel/scheduler/switch/switch_x64.o

CPP_OBJS = \
	cpp/runtime/compat.o

# Multi-language driver objects (Rust and C++) - Optional, only included if enabled
RUST_DRIVER_OBJS = 
CPP_DRIVER_OBJS = 
MULTILANG_DRIVER_SUPPORT_OBJ = 

# Include example drivers only if KERNEL_ENABLE_EXAMPLE_DRIVERS is enabled
# These are test/example drivers and should not be compiled by default
-include .example_drivers_enabled
ifneq ($(CONFIG_ENABLE_EXAMPLE_DRIVERS),)
ifeq ($(CONFIG_ENABLE_EXAMPLE_DRIVERS),y)
RUST_DRIVER_OBJS += rust/drivers/rust_simple_driver.o
CPP_DRIVER_OBJS += cpp/examples/cpp_example.o
MULTILANG_DRIVER_SUPPORT_OBJ += drivers/multilang_drivers.o
CFLAGS += -DKERNEL_ENABLE_EXAMPLE_DRIVERS=1
else
CFLAGS += -DKERNEL_ENABLE_EXAMPLE_DRIVERS=0
endif
else ifeq ($(ENABLE_EXAMPLE_DRIVERS),1)
RUST_DRIVER_OBJS += rust/drivers/rust_simple_driver.o
CPP_DRIVER_OBJS += cpp/examples/cpp_example.o
MULTILANG_DRIVER_SUPPORT_OBJ += drivers/multilang_drivers.o
CFLAGS += -DKERNEL_ENABLE_EXAMPLE_DRIVERS=1
else
CFLAGS += -DKERNEL_ENABLE_EXAMPLE_DRIVERS=0
endif

# All objects (kernel sin tests in-kernel)
ALL_OBJS = $(KERNEL_OBJS) $(MEMORY_OBJS) $(LIB_OBJS) $(INTERRUPT_OBJS) \
           $(DRIVER_OBJS) $(FS_OBJS) $(ARCH_OBJS) $(DISK_OBJS) \
           $(CPP_OBJS) $(CPP_DRIVER_OBJS) $(RUST_DRIVER_OBJS) \
           $(NET_OBJS) $(NET_DRIVER_OBJS) $(SOUND_OBJS) $(BLUETOOTH_OBJS) \
           $(MOUSE_OBJS) $(VBE_OBJS) $(PC_SPEAKER_OBJS) \
           $(STORAGE_ATA_OBJS) $(STORAGE_ATA_BLOCK_OBJS)

# Objetos para kernel con tests in-kernel (make tests / kernel-tests)
# Excluir debug_bins_registry.o y usar debug_bins_registry_test.o (compilado con IR0_KERNEL_TESTS=1)
ALL_OBJS_TEST = $(filter-out debug_bins/debug_bins_registry.o,$(KERNEL_OBJS)) $(KERNEL_TEST_OBJS) $(MEMORY_OBJS) $(LIB_OBJS) $(INTERRUPT_OBJS) \
                $(DRIVER_OBJS) $(FS_OBJS) $(ARCH_OBJS) $(DISK_OBJS) \
                $(CPP_OBJS) $(CPP_DRIVER_OBJS) $(RUST_DRIVER_OBJS) \
                $(NET_OBJS) $(NET_DRIVER_OBJS) $(SOUND_OBJS) $(BLUETOOTH_OBJS) \
                $(MOUSE_OBJS) $(VBE_OBJS) $(PC_SPEAKER_OBJS) \
                $(STORAGE_ATA_OBJS) $(STORAGE_ATA_BLOCK_OBJS)

AUTOCONF_HDR := $(KERNEL_ROOT)/include/generated/autoconf.h
ifneq ($(wildcard $(KERNEL_ROOT)/.config),)
$(AUTOCONF_HDR): $(KERNEL_ROOT)/.config
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --sync >/dev/null
$(ALL_OBJS): $(AUTOCONF_HDR)
$(ALL_OBJS_TEST): $(AUTOCONF_HDR)
endif

# BUILD RULES

# Compile C files
%.o: %.c
	@echo "  CC      $<"
	@$(CC) $(CFLAGS) \
		-DIR0_BUILD_DATE_STRING="\"$(IR0_BUILD_DATE)\"" \
		-DIR0_BUILD_TIME_STRING="\"$(IR0_BUILD_TIME)\"" \
		-DIR0_BUILD_USER_STRING="\"$(IR0_BUILD_USER)\"" \
		-DIR0_BUILD_HOST_STRING="\"$(IR0_BUILD_HOST)\"" \
		-DIR0_BUILD_CC_STRING="\"$(IR0_BUILD_CC)\"" \
		-DIR0_BUILD_NUMBER_STRING="\"$(IR0_BUILD_NUMBER)\"" \
		-c $< -o $@

# Compile C++ files
%.o: %.cpp
	@echo "  CXX     $<"
	@g++ $(CXXFLAGS_COMPILE) -c $< -o $@

# Compile Rust files (using unibuild script)
%.o: %.rs
	@echo "  RUST    $<"
	@$(KERNEL_ROOT)/scripts/unibuild.sh -rust $<

# Compile ASM files
%.o: %.asm
	@echo "  ASM     $<"
	@$(ASM) $(ASMFLAGS) $< -o $@


# Link kernel
kernel-x64.bin: $(ALL_OBJS) arch/x86-64/linker.ld
	@echo "  LD      $@"
	@$(LD) $(LDFLAGS) -o $@ $(ALL_OBJS)
	@echo "✓ Kernel linked: $@"
	@echo "  BUILD   Incrementing build number..."
	@if [ -f .build_number ]; then \
		BUILD_NUM=$$(cat .build_number); \
		BUILD_NUM=$$((BUILD_NUM + 1)); \
		echo $$BUILD_NUM > .build_number; \
	else \
		echo "1" > .build_number; \
	fi

# Create ISO
kernel-x64.iso: kernel-x64.bin arch/x86-64/grub.cfg
	@echo "  ISO     $@"
	@rm -rf iso
	@mkdir -p iso/boot/grub
	@cp arch/x86-64/grub.cfg iso/boot/grub/
	@cp kernel-x64.bin iso/boot/
	@echo "Running grub-mkrescue (will print errors if it fails)..."
	@grub-mkrescue -o $@ iso
	@echo "✓ ISO created: $@"

# Kernel con tests in-kernel (solo al hacer make tests / kernel-tests)
# config.h documents IR0_KERNEL_TESTS; Makefile ensures it for this target
kernel-x64-test.bin: CFLAGS += -DIR0_KERNEL_TESTS=1
kernel-x64-test.bin: $(ALL_OBJS_TEST) arch/x86-64/linker.ld
	@echo "  LD      $@ (with in-kernel tests)"
	@$(LD) $(LDFLAGS) -o $@ $(ALL_OBJS_TEST)
	@echo "✓ Kernel (test) linked: $@"

kernel-x64-test.iso: kernel-x64-test.bin arch/x86-64/grub.cfg
	@echo "  ISO     $@"
	@rm -rf iso_test
	@mkdir -p iso_test/boot/grub
	@cp arch/x86-64/grub.cfg iso_test/boot/grub/
	@cp kernel-x64-test.bin iso_test/boot/kernel-x64.bin
	@grub-mkrescue -o $@ iso_test
	@rm -rf iso_test
	@echo "✓ ISO (test) created: $@"

# Create a raw disk image used by QEMU. If you want a persistent filesystem
# you can format and populate this image separately. This target will
# create a raw disk image if it doesn't already exist.
# Supports filesystem selection via FS=minix|fat32|ext4 and size via SIZE=MB (legacy)
# For new usage, use: make create-disk [filesystem] [size]
disk.img:
	@if [ -f $@ ]; then \
		echo "  DISK    $@ already exists"; \
	else \
		echo "  DISK    creating $@ using scripts/create_disk.sh"; \
		if [ -n "$(FS)" ]; then \
			if [ -n "$(SIZE)" ]; then \
				./scripts/create_disk.sh $(FS) $(SIZE) --output $@; \
			else \
				./scripts/create_disk.sh $(FS) --output $@; \
			fi; \
		else \
			./scripts/create_disk.sh --output $@; \
		fi; \
	fi
	@echo "✓ Disk image ready: $@"

# ============================================
# BUILD CONFIGURATION
# ============================================

# Default values
PARALLEL_JOBS ?= 1
# ARCH is already set at the top of the file

# Enable parallel builds if auto is specified
ifneq (,$(filter auto,$(MAKECMDGOALS)))
    PARALLEL_JOBS := $(shell nproc)
    MAKEOVERRIDES := $(filter-out auto,$(MAKEOVERRIDES))
    .NOTPARALLEL:
endif


# Process architecture parameter (if specified); x86-64 is the only supported port
ifdef arch
    ifneq ($(arch),x86-64)
        $(error Unsupported architecture: $(arch). Only x86-64 is supported.)
    endif
    ARCH := x86-64
    CFLAGS += -DARCH_X86_64
else
    ARCH := x86-64
    CFLAGS += -DARCH_X86_64
endif

# ============================================
# BUILD TARGETS
# ============================================

# Objetivo principal: warnings como errores (replica CI / toolchains estrictos).
ir0: CFLAGS += -Werror

ifeq ($(CONFIG_TOOL_AUTO_RUN_DEPTEST),y)
IR0_PRECHECK_TARGETS := deptest
else
IR0_PRECHECK_TARGETS :=
endif

# Default target
ir0: $(IR0_PRECHECK_TARGETS) kernel-x64.iso

# Build using all available CPU cores
ir0-auto: auto
	@# This is now just a compatibility alias

# Auto build target (used by ir0-auto for compatibility)
.PHONY: auto
auto: ir0

# Windows build target
windows win:
	@echo "Building IR0 Kernel for Windows..."
	@$(MAKE) -f Makefile.win ir0

windows-clean win-clean:
	@echo "Cleaning Windows build artifacts..."
	@$(MAKE) -f Makefile.win clean

# QEMU COMMANDS

# Run with GUI and disk (default) - ALL IR0 SUPPORTED HARDWARE
# Note: This target does NOT call clean-net or rebuild with special flags
# It simply runs the existing kernel ISO. Use 'make run-tap' for TAP networking.
run: kernel-x64.iso disk.img
	@echo "🚀 Running IR0 Kernel with all supported hardware..."
	@echo "   Hardware: RTL8139, SB16, Adlib, ATA/IDE, Serial, PS/2, VGA"
	@# Check if we can write to qemu_debug.log (skip if owned by root or not writable)
	@QEMU_LOG_OPTION=""; \
	if [ -f qemu_debug.log ] && [ ! -w qemu_debug.log ]; then \
		echo "   ⚠️  qemu_debug.log not writable (owned by root?), skipping log file"; \
		QEMU_LOG_OPTION=""; \
	elif touch qemu_debug.log 2>/dev/null; then \
		QEMU_LOG_OPTION="$(QEMU_LOG_FILE)"; \
		rm -f qemu_debug.log; \
	else \
		QEMU_LOG_OPTION=""; \
	fi
	qemu-system-x86_64 -cdrom kernel-x64.iso \
		$(QEMU_HW_IR0_ALL) \
		-m 512M -no-reboot -no-shutdown \
		$(QEMU_DISPLAY) \
		$(QEMU_DEBUG_GUEST) $$QEMU_LOG_OPTION

# Run with GUI and serial debug output - ALL IR0 SUPPORTED HARDWARE
run-debug: kernel-x64.iso disk.img
	@echo "Running IR0 Kernel with debug output and all supported hardware..."
	@echo "   Hardware: RTL8139, SB16, ATA/IDE, Serial, PS/2, VGA"
	@echo "Serial output will appear in this terminal"
	@echo "QEMU GUI will open in separate window"
	@echo "Press Ctrl+C to stop"
	qemu-system-x86_64 -cdrom kernel-x64.iso \
		$(QEMU_HW_IR0_ALL) \
		-m 512M -no-reboot -no-shutdown \
		$(QEMU_DISPLAY) \
		-monitor telnet:127.0.0.1:1234,server,nowait \
		-d guest_errors,int $(QEMU_LOG_FILE)

# Run without disk
run-nodisk: kernel-x64.iso
	@echo "Running IR0 Kernel (no disk)..."
	qemu-system-x86_64 -cdrom kernel-x64.iso \
		-m 512M -no-reboot -no-shutdown \
		-display gtk -serial stdio

# Run in console mode (attach disk image) - ALL IR0 SUPPORTED HARDWARE
run-console: kernel-x64.iso disk.img
	@echo "Running IR0 Kernel (console) with all supported hardware..."
	@echo "   Hardware: RTL8139, SB16, ATA/IDE, Serial, PS/2"
	qemu-system-x86_64 -cdrom kernel-x64.iso \
		$(QEMU_HW_IR0_ALL) \
		-m 512M -no-reboot -no-shutdown \
		$(QEMU_NGRAPHIC)

# Run with TAP networking (permite ping bidireccional, requiere root y bridge configurado)
# Pasos previos (bridge y TAP):
#   1. sudo ip link add br0 type bridge
#   2. sudo ip link set eth0 master br0  (reemplaza eth0 con tu interfaz)
#   3. sudo ip tuntap add tap0 mode tap
#   4. sudo ip link set tap0 master br0
#   5. sudo ip link set br0 up && sudo ip link set tap0 up
run-tap: kernel-x64.iso disk.img
	@echo "🚀 Running IR0 Kernel with TAP networking (full ICMP support)..."
	@echo "   Hardware: RTL8139, ATA/IDE, Serial, PS/2, VGA (audio disabled)"
	@echo "   ⚠️  Requires: root permissions and TAP interface configured"
	@if [ ! -c /dev/net/tun ]; then \
		echo "ERROR: TUN/TAP device not available. Install: sudo modprobe tun"; \
		exit 1; \
	fi
	@echo "   📝 Building kernel with TAP networking support (auto-configure IP)..."
	@$(MAKE) clean-net 2>/dev/null || true
	@$(MAKE) CFLAGS="$(CFLAGS) -DIR0_TAP_NETWORKING" ir0
	@echo "   🎮 Starting QEMU (audio disabled to avoid ALSA errors)..."
	sudo qemu-system-x86_64 -cdrom kernel-x64.iso \
		$(QEMU_NET_RTL8139_TAP) $(QEMU_STORAGE_IDE) $(QEMU_SERIAL_COM1) \
		-m 512M -no-reboot -no-shutdown \
		$(QEMU_DISPLAY) \
		$(QEMU_DEBUG_GUEST) $(QEMU_LOG_FILE)

# Run with ICMP ping support (user-mode networking, no TAP/bridge needed)
# Enables unprivileged ICMP sockets via sysctl so QEMU SLiRP can forward ping.
# Only needs sudo once to set the sysctl; QEMU itself runs unprivileged.
# Guest IP: 10.0.2.15, Gateway/DNS: 10.0.2.2 (always pingable)
# Internet: ping 8.8.8.8 works after sysctl is set.
run-ping: kernel-x64.iso disk.img
	@echo "  PING    Checking ICMP socket permissions..."
	@CURRENT=$$(cat /proc/sys/net/ipv4/ping_group_range 2>/dev/null); \
	if echo "$$CURRENT" | grep -q "^0[[:space:]]"; then \
		echo "          ping_group_range already configured: $$CURRENT"; \
	else \
		echo "          Setting net.ipv4.ping_group_range (requires sudo once)..."; \
		sudo sysctl -w net.ipv4.ping_group_range="0 2147483647" || { \
			echo "ERROR: Could not set ping_group_range. Run manually:"; \
			echo "  sudo sysctl -w net.ipv4.ping_group_range=\"0 2147483647\""; \
			exit 1; \
		}; \
	fi
	@echo "  PING    Launching QEMU with user-mode networking (ICMP enabled)"
	@echo "          Guest: 10.0.2.15 | Gateway: 10.0.2.2 | DNS: 10.0.2.3"
	@echo "          Try: ping 10.0.2.2   (gateway, always works)"
	@echo "          Try: ping 8.8.8.8    (internet, needs sysctl)"
	qemu-system-x86_64 -cdrom kernel-x64.iso \
		$(QEMU_HW_IR0_ALL) \
		-m 512M -no-reboot -no-shutdown \
		$(QEMU_DISPLAY)

# Debug mode (detailed QEMU logging) - ALL IR0 SUPPORTED HARDWARE
debug: kernel-x64.iso disk.img
	@echo "Running IR0 Kernel (debug) with all supported hardware..."
	@echo "   Hardware: RTL8139, SB16, ATA/IDE, Serial, PS/2, VGA"
	qemu-system-x86_64 -cdrom kernel-x64.iso \
		$(QEMU_HW_IR0_ALL) \
		-m 512M -no-reboot -no-shutdown \
		$(QEMU_DISPLAY) \
		-d int,cpu_reset,guest_errors $(QEMU_LOG_FILE)

# QEMU con servidor GDB: inspección de memoria, breakpoints, single-step.
run-gdb: kernel-x64.iso disk.img
	@echo "  GDB     QEMU waiting for GDB on localhost:1234"
	@echo "          In another terminal run:"
	@echo "            gdb -x scripts/kernel.gdb"
	@echo "          Breakpoints on kmain and kernel_panic are set automatically."
	qemu-system-x86_64 -cdrom kernel-x64.iso \
		$(QEMU_SERIAL_COM1) -drive file=disk.img,format=raw,if=ide,index=0 \
		-m 512M -no-reboot -no-shutdown -display none -net none \
		-s -S

# Create disk image (wrapper for scripts/create_disk.sh)
# Usage: make create-disk [filesystem] [size]
# Examples:
#   make create-disk              # Create 200MB MINIX disk (default)
#   make create-disk minix 500    # Create 500MB MINIX disk
#   make create-disk fat32        # Create FAT32 disk (default size)
#   make create-disk fat32 500    # Create 500MB FAT32 disk
#   make create-disk ext4 1000    # Create 1GB ext4 disk
#   make create-disk hints        # Show help
create-disk:
	@ARGS="$(filter-out $@,$(MAKECMDGOALS))"; \
	if [ -z "$$ARGS" ]; then \
		./scripts/create_disk.sh "$(TOOL_DEFAULT_DISK_FS_NAME)" "$(CONFIG_TOOL_DEFAULT_DISK_SIZE_MB)"; \
	elif [ "$$ARGS" = "hints" ] || [ "$$ARGS" = "help" ]; then \
		./scripts/create_disk.sh --help; \
	else \
		./scripts/create_disk.sh $$ARGS; \
	fi
	@if [ "$$ARGS" != "hints" ] && [ "$$ARGS" != "help" ]; then \
		echo "Disk image is ready: disk.img"; \
	fi

# Delete disk image (useful to reset persistent disk for QEMU)
# Usage: make delete-disk [filesystem] [filename]
# Examples:
#   make delete-disk              # Delete disk.img (default)
#   make delete-disk minix        # Delete disk.img
#   make delete-disk fat32        # Delete fat32.img
#   make delete-disk fat32 fat32.img  # Delete fat32.img explicitly
delete-disk:
	@ARGS="$(filter-out $@,$(MAKECMDGOALS))"; \
	if [ -z "$$ARGS" ]; then \
		./scripts/delete_disk.sh; \
	else \
		./scripts/delete_disk.sh $$ARGS; \
	fi

# Load Init binary into virtual disk
# Usage: make load-init [filesystem] [disk_image] [init_binary]
# Defaults: filesystem=auto-detect, disk_image=disk.img, init_binary=setup/pid1/init
# Supported filesystems: minix, fat32, ext4
# Note: Requires root privileges (mounts filesystem)
# Examples:
#   sudo make load-init                    # Auto-detect, use disk.img
#   sudo make load-init fat32              # Use fat32.img
#   sudo make load-init fat32 fat32.img    # Explicit filesystem and disk
#   make load-init hints                   # Show help
load-init:
	@ARGS="$(filter-out $@,$(MAKECMDGOALS))"; \
	if [ -z "$$ARGS" ]; then \
		./scripts/load_init.sh; \
	elif [ "$$ARGS" = "hints" ] || [ "$$ARGS" = "help" ]; then \
		./scripts/load_init.sh --help; \
	else \
		./scripts/load_init.sh $$ARGS; \
	fi

# Remove Init binary from virtual disk
# Usage: make remove-init [filesystem] [disk_image]
# Defaults: filesystem=auto-detect, disk_image=disk.img
# Supported filesystems: minix, fat32, ext4
# Note: Requires root privileges (mounts filesystem)
# Examples:
#   sudo make remove-init                  # Auto-detect, use disk.img
#   sudo make remove-init fat32            # Use fat32.img
#   sudo make remove-init fat32 fat32.img  # Explicit filesystem and disk
#   make remove-init hints                 # Show help
remove-init:
	@ARGS="$(filter-out $@,$(MAKECMDGOALS))"; \
	if [ -z "$$ARGS" ]; then \
		./scripts/remove_init.sh; \
	elif [ "$$ARGS" = "hints" ] || [ "$$ARGS" = "help" ]; then \
		./scripts/remove_init.sh --help; \
	else \
		./scripts/remove_init.sh $$ARGS; \
	fi

# CLEAN

clean:
	@echo "Cleaning build artifacts..."
	@find . -name "*.o" -type f -delete
	@find . -name "*.d" -type f -delete
	@find . -name "*.bin" -type f -delete
	@find . -name "*.su" -type f -delete
	@rm -f kernel-x64.iso kernel-x64-test.iso
	@rm -f kernel-x64.map kernel-x64.disasm compile_commands.json
	@rm -rf iso iso_test
	@$(MAKE) -C tests/kernel_memsafe clean 2>/dev/null || true
	@echo "Clean done."

# TEST SUITE — Compila todos los artefactos de test (estilo kernels de producción).
# - Código kernel en host para Valgrind (make kernel-memsafe)
# - Kernel con tests in-kernel (ktest) para make kernel-tests
# - Análisis del binario de arranque (make kernel-analyze → kernel-x64.bin)
tests: kernel-x64-test.bin
	@echo "  TEST    Building kernel-memsafe (kernel code under Valgrind)..."
	@$(MAKE) -C tests/kernel_memsafe KERNEL_ROOT=$(KERNEL_ROOT) all
	@echo "✓ Tests built: tests/kernel_memsafe/ir0_kernel_memsafe, kernel-x64-test.bin"

# Valgrind sobre código del kernel compilado para host (resource_registry, etc.)
kernel-memsafe:
	@echo "  KERNEL-MEMSAFE  Building kernel code for host and running Valgrind..."
	@$(MAKE) -C tests/kernel_memsafe KERNEL_ROOT=$(KERNEL_ROOT) memsafe
	@echo "✓ kernel-memsafe passed"

# Batería in-kernel al estilo KUnit: tests se ejecutan al arranque (no dependen de la shell).
# QEMU headless, sin red. El kernel (kernel-x64-test.bin) llama kernel_test_run_all() en boot.
kernel-tests: kernel-x64-test.iso disk.img
	@echo "  KTEST   Running in-kernel test suite at boot (KUnit-style)..."
	@timeout 40 $(QEMU) -cdrom kernel-x64-test.iso -drive file=disk.img,format=raw,if=ide,index=0 -serial stdio -display none -m 128M -no-reboot -net none 2>&1 | tee /tmp/ktest.log; \
	grep -q "All .* test(s) passed" /tmp/ktest.log && ! grep -q "Some tests FAILED" /tmp/ktest.log && ! grep -q "not ok " /tmp/ktest.log; \
	if [ $$? -eq 0 ]; then echo "✓ kernel-tests passed"; exit 0; else echo "✗ kernel-tests FAILED"; exit 1; fi

# Análisis del binario del kernel: secciones (size -A), símbolos no definidos, kmain.
kernel-analyze: kernel-x64.bin
	@echo "  ANALYZE kernel-x64.bin"
	@echo "----------------------------------------"
	@echo "Section sizes (size -A):"
	@size -A kernel-x64.bin
	@echo "----------------------------------------"
	@echo "Undefined symbols (nm --undefined-only, first 20):"
	@nm --undefined-only kernel-x64.bin 2>/dev/null | head -20 || true
	@UNDEF=$$(nm --undefined-only kernel-x64.bin 2>/dev/null | wc -l); echo "Undefined symbol count: $$UNDEF"
	@echo "----------------------------------------"
	@echo "Entry symbol:"
	@nm kernel-x64.bin 2>/dev/null | grep -E ' [Tt] kmain$$' || true
	@if nm kernel-x64.bin 2>/dev/null | grep -q ' [Tt] kmain$$'; then echo "✓ kernel-analyze passed (kmain present)"; else echo "✗ kernel-analyze FAILED (kmain not found)"; exit 1; fi

# Salud del sistema: ejecuta toda la batería (kernel-analyze, kernel-memsafe, kernel-tests).
# Útil para CI o comprobar que el árbol está sano antes de un commit.
health: kernel-analyze
	@echo ""
	@echo "  HEALTH  Running full test suite..."
	@$(MAKE) kernel-memsafe && $(MAKE) kernel-tests
	@echo ""
	@echo "✓ health passed (kernel-analyze, kernel-memsafe, kernel-tests)"

# Minimal permanent build matrix for modular configs.
build-matrix-min:
	@echo "  MATRIX  defconfig"
	@$(MAKE) defconfig >/dev/null
	@$(MAKE) -s kernel-x64.bin >/dev/null
	@echo "  MATRIX  tiny preset"
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --preset tiny >/dev/null
	@$(MAKE) -s kernel-x64.bin >/dev/null
	@echo "  MATRIX  networking disabled"
	@$(MAKE) defconfig >/dev/null
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --set ENABLE_NETWORKING=n INIT_NETWORK_STACK=n >/dev/null
	@$(MAKE) -s kernel-x64.bin >/dev/null
	@echo "  MATRIX  storage fully disabled"
	@$(MAKE) defconfig >/dev/null
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --set ENABLE_STORAGE_ATA=n ENABLE_STORAGE_ATA_BLOCK=n INIT_STORAGE_ATA=n INIT_STORAGE_ATA_BLOCK=n >/dev/null
	@$(MAKE) -s kernel-x64.bin >/dev/null
	@echo "  MATRIX  storage core without block layer"
	@$(MAKE) defconfig >/dev/null
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --set ENABLE_STORAGE_ATA=y ENABLE_STORAGE_ATA_BLOCK=n INIT_STORAGE_ATA=y INIT_STORAGE_ATA_BLOCK=n >/dev/null
	@$(MAKE) -s kernel-x64.bin >/dev/null
	@echo "  MATRIX  tmpfs-only root"
	@$(MAKE) defconfig >/dev/null
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --set ENABLE_FS_MINIX=n ENABLE_FS_TMPFS=y ROOT_FILESYSTEM=tmpfs >/dev/null
	@$(MAKE) -s kernel-x64.bin >/dev/null
	@echo "  MATRIX  scheduler policy 1"
	@$(MAKE) defconfig >/dev/null
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --set SCHEDULER_POLICY=1 >/dev/null
	@$(MAKE) -s kernel-x64.bin >/dev/null
	@echo "  MATRIX  scheduler policy 2"
	@$(MAKE) defconfig >/dev/null
	@python3 $(KERNEL_ROOT)/scripts/kconfig/menuconfig.py --set SCHEDULER_POLICY=2 >/dev/null
	@$(MAKE) -s kernel-x64.bin >/dev/null
	@echo "✓ build-matrix-min passed"

config-sim:
	@python3 $(KERNEL_ROOT)/scripts/kconfig/config_sim.py

runtime-net-check:
	@echo "  RUNTIME  network smoke (QEMU user-net)"
	@$(MAKE) -s defconfig >/dev/null
	@python3 $(KERNEL_ROOT)/scripts/kconfig/config_sim.py \
		--symbols ENABLE_NETWORKING,INIT_NETWORK_STACK \
		--max-cases 2 \
		--build-cmd "make -s kernel-x64.iso disk.img" \
		--runtime-cmd "python3 $(KERNEL_ROOT)/scripts/net_runtime_smoke.py --timeout-sec 25"
	@echo "✓ runtime-net-check passed"

arch-guard:
	@python3 $(KERNEL_ROOT)/scripts/architecture_guard.py

repo-hygiene-guard:
	@python3 $(KERNEL_ROOT)/scripts/repo_hygiene_guard.py

build-matrix-full:
	@$(MAKE) -s build-matrix-min
	@echo "  MATRIX  boolean config simulation (24 cases)"
	@python3 $(KERNEL_ROOT)/scripts/kconfig/config_sim.py --max-cases 24 --build-cmd "make -s kernel-x64.bin"
	@echo "  MATRIX  runtime network smoke checks"
	@$(MAKE) -s runtime-net-check
	@echo "  MATRIX  architecture guardrails"
	@$(MAKE) -s arch-guard
	@echo "  MATRIX  repository hygiene guardrails"
	@$(MAKE) -s repo-hygiene-guard
	@echo "✓ build-matrix-full passed"

scale-readiness-gate:
	@$(MAKE) -s build-matrix-full
	@echo "✓ scale-readiness-gate passed"

# Clean only network objects
clean-net:
	@echo "Cleaning network objects for TAP rebuild..."
	@rm -f net/*.o

# HELP

# DEV TOOLING

format:
	@echo "  FMT     Formatting *.c *.h ..."
	@find . \( -name "*.c" -o -name "*.h" \) \
		-not -path "./setup/*" -not -path "./build/*" -not -path "./.git/*" \
		| xargs clang-format -i
	@echo "✓ Format done"

# Análisis estático con cppcheck (opcional).
analyze:
	@if command -v cppcheck >/dev/null 2>&1; then \
		echo "  CPPCHECK --enable=warning,style --quiet ..."; \
		cppcheck --enable=warning,style --quiet -i.git -iiso -iiso_test .; \
	else \
		echo "cppcheck is not installed; skipping static analysis."; \
		echo "Install cppcheck to enable this target (e.g. apt install cppcheck, dnf install cppcheck, pacman -S cppcheck, brew install cppcheck)."; \
	fi

compile-commands:
	@echo "  CC_JSON Generating compile_commands.json ..."
	@echo "[" > compile_commands.json
	@first=true; count=0; \
	for src in $(patsubst %.o,%.c,$(filter %.o,$(ALL_OBJS))); do \
		if [ -f "$$src" ]; then \
			if [ "$$first" = true ]; then first=false; else echo "," >> compile_commands.json; fi; \
			printf '  { "directory": "%s", "file": "%s", "command": "%s %s -c %s" }' \
				"$(CURDIR)" "$$src" "$(CC)" "$(CFLAGS)" "$$src" >> compile_commands.json; \
			count=$$((count + 1)); \
		fi; \
	done; \
	for src in $(patsubst %.o,%.cpp,$(filter %.o,$(ALL_OBJS))); do \
		if [ -f "$$src" ]; then \
			if [ "$$first" = true ]; then first=false; else echo "," >> compile_commands.json; fi; \
			printf '  { "directory": "%s", "file": "%s", "command": "%s %s -c %s" }' \
				"$(CURDIR)" "$$src" "g++" "$(CXXFLAGS_COMPILE)" "$$src" >> compile_commands.json; \
			count=$$((count + 1)); \
		fi; \
	done; \
	echo "" >> compile_commands.json; \
	echo "]" >> compile_commands.json; \
	echo "✓ compile_commands.json generated ($$count entries)"

disasm: kernel-x64.bin
	@echo "  OBJDUMP kernel-x64.disasm ..."
	@objdump -d -S kernel-x64.bin > kernel-x64.disasm
	@echo "✓ Disassembly: kernel-x64.disasm ($(shell wc -l < kernel-x64.disasm 2>/dev/null || echo ?) lines)"

stack-usage:
	@echo "  STACK   Rebuilding with -fstack-usage ..."
	@$(MAKE) clean
	@$(MAKE) CFLAGS="$(CFLAGS) -fstack-usage" kernel-x64.bin
	@echo ""
	@echo "Top 30 stack consumers:"
	@echo "-----------------------------------------------"
	@find . -name "*.su" -exec cat {} + 2>/dev/null | sort -t: -k3 -rn | head -30
	@echo ""

help:
	@echo "╔════════════════════════════════════════════════════════════╗"
	@echo "║               IR0 KERNEL - BUILD SYSTEM                    ║"
	@echo "╚════════════════════════════════════════════════════════════╝"
	@echo ""
	@echo "Build:"
	@echo "  make ir0              Build kernel ISO (-Werror)"
	@echo "  make all              Build kernel ISO"
	@echo "  make windows          Build kernel for Windows (cross-compile)"
	@echo "  make clean            Clean all build artifacts"
	@echo ""
	@echo "Run:"
	@echo "  make run              Run with GUI + disk (recommended)"
	@echo "  make run-debug        Run with GUI + serial debug output"
	@echo "  make run-nodisk       Run without disk"
	@echo "  make run-console      Run in console mode"
	@echo "  make run-tap          Run with TAP networking (requires root + bridge)"
	@echo "  make run-ping         Run with ICMP ping support (user-mode, no TAP)"
	@echo "  make run-gdb          Run QEMU waiting for GDB (localhost:1234)"
	@echo ""
	@echo "Dev Tooling:"
	@echo "  make format           Format all C/H files with clang-format"
	@echo "  make analyze          Run cppcheck (warning,style) if installed"
	@echo "  make compile-commands Generate compile_commands.json for LSP/IDE"
	@echo "  make disasm           Disassemble kernel binary (objdump -d -S)"
	@echo "  make stack-usage      Rebuild with -fstack-usage and show top consumers"
	@echo ""
	@echo "Utilities:"
	@echo "  make menuconfig       Kernel configuration menu (curses TUI)"
	@echo "  make menuconfig-en    Open menuconfig with English UI"
	@echo "  make menuconfig-es    Open menuconfig with Spanish UI"
	@echo "  make defconfig        Write default .config (all features enabled)"
	@echo "  make deptest          Check all dependencies (run this first!)"
	@echo "  make tests            Build all test artifacts (tests/, kernel with ktest)"
	@echo "  make kernel-memsafe   Run Valgrind over kernel code (tests/kernel_memsafe)"
	@echo "  make kernel-tests     Run in-kernel test suite in QEMU (kernel-x64-test.iso)"
	@echo "  make kernel-analyze   Analyze kernel-x64.bin (size -A, undefined symbols; checks kmain)"
	@echo "  make health           Full health check: kernel-analyze + kernel-memsafe + kernel-tests"
	@echo "  make build-matrix-min Build defconfig/tiny/net-off/storage variants"
	@echo "  make runtime-net-check Runtime network smoke checks (QEMU)"
	@echo "  make build-matrix-full Extended matrix + runtime + guards"
	@echo "  make scale-readiness-gate Final stabilization gate"
	@echo "  make config-sim       Simulate subsystem on/off combinations"
	@echo "  make arch-guard       Enforce include/facade architecture constraints"
	@echo "  make repo-hygiene-guard Enforce tracked-artifact/docs hygiene rules"
	@echo "  make create-disk      Create virtual disk (MINIX by default)"
	@echo "  make create-disk hints  Show create-disk help"
	@echo "  make delete-disk      Delete virtual disk"
	@echo "  make load-init        Load Init binary into disk (requires sudo)"
	@echo "  make load-init hints  Show load-init help"
	@echo "  make remove-init      Remove Init binary from disk (requires sudo)"
	@echo "  make remove-init hints  Show remove-init help"
	@echo "  make help             Show this help"
	@echo ""
	@echo "Extern Drivers (Multi-Language):"
	@echo "  make en-ext-drv       Enable example drivers for next build"
	@echo "  make dis-ext-drv      Disable example drivers"
	@echo "  Note: Extern drivers are optional and disabled by default"
	@echo ""
	@echo "Unibuild - Isolated Compilation:"
	@echo "  C files (can compile multiple at once):"
	@echo "    make unibuild <file1.c> [file2.c] ..."
	@echo "    make unibuild-win <file1.c> [file2.c] ...     (Windows)"
	@echo ""
	@echo "  C++ files (can compile multiple at once):"
	@echo "    make unibuild-cpp <file1.cpp> [file2.cpp] ..."
	@echo "    make unibuild-cpp-win <file1.cpp> [file2.cpp] ...  (Windows)"
	@echo ""
	@echo "  Rust files (can compile multiple at once):"
	@echo "    make unibuild-rust <file1.rs> [file2.rs] ..."
	@echo "    make unibuild-rust-win <file1.rs> [file2.rs] ...   (Windows)"
	@echo ""
	@echo "  Clean:"
	@echo "    make unibuild-clean <file>"
	@echo ""
	@echo "  Examples:"
	@echo "    make unibuild fs/tmpfs.c"
	@echo "    make unibuild fs/tmpfs.c fs/vfs.c fs/path.c"
	@echo "    make unibuild-cpp cpp/examples/cpp_example.cpp"
	@echo "    make unibuild-rust rust/drivers/rust_example_driver.rs"
	@echo "    make unibuild-win drivers/IO/ps2.c"
	@echo "    make unibuild-cpp-win cpp/examples/cpp_example.cpp"
	@echo ""
	@echo "  Note: You can also use \"file1 file2\" syntax"
	@echo ""
	@echo "Quick start: make run"
	@echo ""

# DEPENDENCY TEST

deptest:
	@$(KERNEL_ROOT)/scripts/deptest.sh

# UNIBUILD - ISOLATED FILE COMPILATION

# Helper to get file arguments (supports multiple files from FILE= or positional)
# Usage in targets: $(call get-file-arg)
define get-file-arg
$(if $(FILE),$(FILE),$(filter-out $@,$(MAKECMDGOALS)))
endef

# Standard C compilation (supports multiple files)
unibuild:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild <file1.c> [file2.c] ..."; \
		echo "   Or: make unibuild \"<file1.c>  <file2.c>\""; \
		echo "Example: make unibuild fs/tmpfs.c"; \
		echo "Example: make unibuild fs/tmpfs.c fs/vfs.c"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh $$FILE_ARG

# C++ compilation (supports multiple files)
unibuild-cpp:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild-cpp <file1.cpp> [file2.cpp] ..."; \
		echo "   Or: make unibuild-cpp \"<file1.cpp> <file2.cpp>\""; \
		echo "Example: make unibuild-cpp cpp/examples/cpp_example.cpp"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh -cpp $$FILE_ARG

# Rust compilation (supports multiple files)
unibuild-rust:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild-rust <file1.rs> [file2.rs] ..."; \
		echo "   Or: make unibuild-rust \"<file1.rs> <file2.rs>\""; \
		echo "Example: make unibuild-rust rust/drivers/rust_example_driver.rs"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh -rust $$FILE_ARG

# Windows cross-compilation (C, supports multiple files)
unibuild-win:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild-win <file1.c> [file2.c] ..."; \
		echo "   Or: make unibuild-win \"<file1.c> <file2.c>\""; \
		echo "Example: make unibuild-win drivers/IO/ps2.c"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh -win $$FILE_ARG

# Windows cross-compilation (C++, supports multiple files)
unibuild-cpp-win:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild-cpp-win <file1.cpp> [file2.cpp] ..."; \
		echo "   Or: make unibuild-cpp-win \"<file1.cpp> <file2.cpp>\""; \
		echo "Example: make unibuild-cpp-win cpp/examples/cpp_example.cpp"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh -win -cpp $$FILE_ARG

# Windows cross-compilation (Rust, supports multiple files)
unibuild-rust-win:
	@FILE_ARG="$(call get-file-arg)"; \
	if [ -z "$$FILE_ARG" ] && [ -n "$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)" ]; then \
		FILE_ARG="$(CONFIG_TOOL_UNIBUILD_DEFAULT_FILES)"; \
	fi; \
	if [ -n "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
		FILTERED=""; \
		for f in $$FILE_ARG; do \
			if [ "$$f" != "$(CONFIG_TOOL_UNIBUILD_EXCLUDE_FILE)" ]; then \
				FILTERED="$$FILTERED $$f"; \
			fi; \
		done; \
		FILE_ARG="$$FILTERED"; \
	fi; \
	if [ -z "$$FILE_ARG" ]; then \
		echo "Error: No file specified"; \
		echo "Usage: make unibuild-rust-win <file1.rs> [file2.rs] ..."; \
		echo "   Or: make unibuild-rust-win \"<file1.rs> <file2.rs>\""; \
		echo "Example: make unibuild-rust-win rust/drivers/rust_example_driver.rs"; \
		exit 1; \
	fi; \
	$(KERNEL_ROOT)/scripts/unibuild.sh -win -rust $$FILE_ARG

# Catch-all target to prevent make from complaining about unknown targets (for positional args)
%:
	@:

unibuild-clean:
	@if [ -z "$(FILE)" ]; then \
		echo "Error: FILE parameter required"; \
		echo "Usage: make unibuild-clean <source_file>"; \
		echo "Example: make unibuild-clean fs/tmpfs.c"; \
		exit 1; \
	fi
	@$(KERNEL_ROOT)/scripts/unibuild-clean.sh "$(FILE)"

# TEST DRIVERS - MULTI-LANGUAGE EXAMPLES (OPTIONAL)

# Rust test driver
RUST_TEST_DRIVER = rust/drivers/rust_example_driver.rs
RUST_TEST_OBJ = rust/drivers/rust_example_driver.o

# C++ test driver
CPP_TEST_DRIVER = cpp/examples/cpp_example.cpp
CPP_TEST_OBJ = cpp/examples/cpp_example.o

# Enable example drivers for next build
en-ext-drv:
	@echo "ENABLE_EXAMPLE_DRIVERS=1" > .example_drivers_enabled
	@echo "✓ Example drivers enabled - will be compiled on next build"

# Disable example drivers
dis-ext-drv:
	@rm -f .example_drivers_enabled
	@echo "✓ Example drivers disabled - will not be compiled"

# Compile Rust test driver using unibuild
test-driver-rust: $(RUST_TEST_DRIVER)
	@echo "🦀 Compiling Rust test driver with unibuild..."
	@$(KERNEL_ROOT)/scripts/unibuild.sh -rust $(RUST_TEST_DRIVER)
	@if [ -f $(RUST_TEST_OBJ) ]; then \
		echo "✓ Rust driver compiled: $(RUST_TEST_OBJ)"; \
	else \
		echo "✗ Rust driver compilation failed"; \
		exit 1; \
	fi

# Compile C++ test driver using unibuild
test-driver-cpp: $(CPP_TEST_DRIVER)
	@echo "➕ Compiling C++ test driver with unibuild..."
	@$(KERNEL_ROOT)/scripts/unibuild.sh -cpp $(CPP_TEST_DRIVER)
	@if [ -f $(CPP_TEST_OBJ) ]; then \
		echo "✓ C++ driver compiled: $(CPP_TEST_OBJ)"; \
	else \
		echo "✗ C++ driver compilation failed"; \
		exit 1; \
	fi

# Compile all test drivers (standalone compilation, not included in kernel)
test-drivers: test-driver-rust test-driver-cpp
	@echo ""
	@echo "╔════════════════════════════════════════════════════════════╗"
	@echo "║          TEST DRIVERS COMPILATION COMPLETE                 ║"
	@echo "╚════════════════════════════════════════════════════════════╝"
	@echo ""
	@echo "✓ Rust driver:  $(RUST_TEST_OBJ)"
	@echo "✓ C++ driver:   $(CPP_TEST_OBJ)"
	@echo ""
	@echo "Note: These are standalone objects. To include in kernel build:"
	@echo "      make en-ext-drv && make ir0"
	@echo "      make dis-ext-drv && make ir0"
	@echo ""

# Clean test driver objects
# Clean test driver objects
test-drivers-clean:
	@echo "Cleaning test driver objects..."
	@if [ -n "$(RUST_ONLY)" ]; then \
		rm -f $(RUST_TEST_OBJ); \
		echo "✓ Rust driver objects cleaned"; \
	elif [ -n "$(CPP_ONLY)" ]; then \
		rm -f $(CPP_TEST_OBJ); \
		echo "✓ C++ driver objects cleaned"; \
	else \
		rm -f $(RUST_TEST_OBJ); \
		rm -f $(CPP_TEST_OBJ); \
		echo "✓ All test driver objects cleaned"; \
	fi


# PHONY TARGETS

.PHONY: all clean run run-debug run-tap run-nodisk run-console run-gdb debug create-disk delete-disk load-init remove-init help \
        unibuild unibuild-cpp unibuild-rust unibuild-win unibuild-cpp-win unibuild-rust-win unibuild-clean \
        ir0 ir0-auto auto windows win windows-clean win-clean deptest menuconfig menuconfig-en menuconfig-es defconfig \
        en-ext-drv dis-ext-drv \
        test-driver-rust test-driver-cpp test-drivers test-drivers-clean \
        tests kernel-memsafe kernel-tests kernel-analyze analyze health build-matrix-min build-matrix-full config-sim arch-guard repo-hygiene-guard \
        runtime-net-check scale-readiness-gate \
        format compile-commands disasm stack-usage clean-net \
        run-ping

# Include dependency files
-include $(ALL_OBJS:.o=.d)
