# Makefile simple para test del teclado
CC = gcc
ASM = nasm
LD = ld

CFLAGS = -m64 -mcmodel=kernel -mno-red-zone -mno-mmx -mno-sse -mno-sse2
CFLAGS += -nostdlib -nostdinc -fno-builtin -fno-stack-protector -fno-pic -nodefaultlibs -ffreestanding
CFLAGS += -I./includes -I./includes/ir0 -I./arch/common -I./arch/x86-64/include -I./setup -I./memory -I./memory/arch/x86-64 -I./interrupt -I./drivers -I./fs -I./kernel -I./examples
CFLAGS += -Wall -Wextra -O0

ASMFLAGS = -f elf64
LDFLAGS = -m elf_x86_64 -T arch/x86-64/linker.ld

# Objetos necesarios para el test
OBJS = test_keyboard.o \
       includes/ir0/print.o \
       includes/ir0/logging.o \
       includes/ir0/validation.o \
       includes/string.o \
       interrupt/arch/idt.o \
       interrupt/arch/pic.o \
       interrupt/arch/isr_handlers.o \
       interrupt/arch/keyboard.o \
       includes/ir0/panic/panic.o \
       memory/bump_allocator.o \
       memory/paging_x64.o \
       arch/x86-64/asm/boot_x64.o \
       arch/x86-64/sources/arch_x64.o \
       arch/x86-64/sources/idt_arch_x64.o \
       arch/x86-64/sources/fault.o \
       arch/x86-64/sources/tss_x64.o \
       interrupt/arch/x86-64/isr_stubs_64.o

# Target principal
all: test-keyboard.bin

# Compilar el test
test_keyboard.o: test_keyboard.c
	$(CC) $(CFLAGS) -c $< -o $@

# Enlazar el kernel
test-keyboard.bin: $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $(OBJS)
	@echo "Test kernel compilado: $@"

# Crear ISO
test-keyboard.iso: test-keyboard.bin
	@mkdir -p iso-test/boot/grub
	@cp arch/x86-64/grub.cfg iso-test/boot/grub/
	@cp test-keyboard.bin iso-test/boot/
	@grub-mkrescue -o $@ iso-test
	@echo "ISO creado: $@"

# Ejecutar en QEMU
run: test-keyboard.iso
	qemu-system-x86_64 -cdrom test-keyboard.iso -m 512M -no-reboot -no-shutdown -display gtk

# Limpiar
clean:
	rm -f test_keyboard.o test-keyboard.bin test-keyboard.iso
	rm -rf iso-test

.PHONY: all run clean
