#!/usr/bin/env bash
set -euo pipefail

echo "IR0 real-hardware smoke checklist"
echo "================================="
echo ""
echo "Preconditions:"
echo "  1) Build latest image: make -s kernel-x64.iso disk.img"
echo "  2) Boot on target x86 hardware with serial capture enabled"
echo "  3) Reach debug shell prompt"
echo ""
echo "Run these commands in debug shell and capture output:"
echo "  - uname"
echo "  - lsdrv"
echo "  - lsblk"
echo "  - lshw"
echo "  - ifconfig"
echo "  - route"
echo "  - netstat"
echo "  - blue adapter"
echo "  - lsblue"
echo "  - mount none /mnt/tmp tmpfs"
echo "  - mount /dev/simple0 /mnt/simple simplefs"
echo "  - mount /dev/fat0 /mnt/fat fat16"
echo "  - mount"
echo "  - dmesg"
echo ""
echo "Pass criteria:"
echo "  - No panic/oops in serial log"
echo "  - lsblk/lshw show coherent disk model and size columns"
echo "  - ifconfig/route print either valid data or explicit degraded hints"
echo "  - bluetooth commands print either topology data or explicit degraded hints"
echo "  - mount output includes entries for /mnt/tmp, /mnt/simple and /mnt/fat"
echo "  - dmesg does not show repeated fatal driver init errors"
echo ""
echo "Tip: keep per-machine logs under tests/smoke/logs/<machine>.log for regressions."
