/* SPDX-License-Identifier: GPL-3.0-only */
/**
 * IR0 Kernel — Core system software
 * Copyright (C) 2026  Iván Rodriguez
 *
 * File: syscall_decode.c
 * Description: Native Linux x86-64 syscall-number decoder backend.
 */

#include <ir0/syscall_id.h>
#include <ir0/syscall_linux.h>

enum ir0_syscall_id syscall_decode_number(uint64_t abi_number)
{
	switch (abi_number)
	{
	case __NR_accept: return IR0_SYSCALL_ACCEPT;
	case __NR_accept4: return IR0_SYSCALL_ACCEPT4;
	case __NR_access: return IR0_SYSCALL_ACCESS;
	case __NR_alarm: return IR0_SYSCALL_ALARM;
	case __NR_arch_prctl: return IR0_SYSCALL_ARCH_PRCTL;
	case __NR_bind: return IR0_SYSCALL_BIND;
	case __NR_brk: return IR0_SYSCALL_BRK;
	case __NR_chdir: return IR0_SYSCALL_CHDIR;
	case __NR_chmod: return IR0_SYSCALL_CHMOD;
	case __NR_chown: return IR0_SYSCALL_CHOWN;
	case __NR_chroot: return IR0_SYSCALL_CHROOT;
	case __NR_clock_gettime: return IR0_SYSCALL_CLOCK_GETTIME;
	case __NR_clock_gettime64: return IR0_SYSCALL_CLOCK_GETTIME64;
	case __NR_clone: return IR0_SYSCALL_CLONE;
	case __NR_close: return IR0_SYSCALL_CLOSE;
	case __NR_connect: return IR0_SYSCALL_CONNECT;
	case __NR_console_clear: return IR0_SYSCALL_EXTENSION_CONSOLE_CLEAR;
	case __NR_console_scroll: return IR0_SYSCALL_EXTENSION_CONSOLE_SCROLL;
	case __NR_dup: return IR0_SYSCALL_DUP;
	case __NR_dup2: return IR0_SYSCALL_DUP2;
	case __NR_dup3: return IR0_SYSCALL_DUP3;
	case __NR_epoll_create: return IR0_SYSCALL_EPOLL_CREATE;
	case __NR_epoll_create1: return IR0_SYSCALL_EPOLL_CREATE1;
	case __NR_epoll_ctl: return IR0_SYSCALL_EPOLL_CTL;
	case __NR_epoll_pwait: return IR0_SYSCALL_EPOLL_PWAIT;
	case __NR_epoll_wait: return IR0_SYSCALL_EPOLL_WAIT;
	case __NR_eventfd2: return IR0_SYSCALL_EVENTFD2;
	case __NR_execve: return IR0_SYSCALL_EXECVE;
	case __NR_execveat: return IR0_SYSCALL_EXECVEAT;
	case __NR_exit: return IR0_SYSCALL_EXIT;
	case __NR_exit_group: return IR0_SYSCALL_EXIT_GROUP;
	case __NR_faccessat: return IR0_SYSCALL_FACCESSAT;
	case __NR_fchdir: return IR0_SYSCALL_FCHDIR;
	case __NR_fchmod: return IR0_SYSCALL_FCHMOD;
	case __NR_fchmodat: return IR0_SYSCALL_FCHMODAT;
	case __NR_fchown: return IR0_SYSCALL_FCHOWN;
	case __NR_fchownat: return IR0_SYSCALL_FCHOWNAT;
	case __NR_fcntl: return IR0_SYSCALL_FCNTL;
	case __NR_fdatasync: return IR0_SYSCALL_FDATASYNC;
	case __NR_flock: return IR0_SYSCALL_FLOCK;
	case __NR_fork: return IR0_SYSCALL_FORK;
	case __NR_fstat: return IR0_SYSCALL_FSTAT;
	case __NR_fstatfs: return IR0_SYSCALL_FSTATFS;
	case __NR_fsync: return IR0_SYSCALL_FSYNC;
	case __NR_ftruncate: return IR0_SYSCALL_FTRUNCATE;
	case __NR_futex: return IR0_SYSCALL_FUTEX;
	case __NR_get_robust_list: return IR0_SYSCALL_GET_ROBUST_LIST;
	case __NR_getcwd: return IR0_SYSCALL_GETCWD;
	case __NR_getdents: return IR0_SYSCALL_GETDENTS;
	case __NR_getdents64: return IR0_SYSCALL_GETDENTS64;
	case __NR_getegid: return IR0_SYSCALL_GETEGID;
	case __NR_geteuid: return IR0_SYSCALL_GETEUID;
	case __NR_getgid: return IR0_SYSCALL_GETGID;
	case __NR_getgroups: return IR0_SYSCALL_GETGROUPS;
	case __NR_getitimer: return IR0_SYSCALL_GETITIMER;
	case __NR_getpeername: return IR0_SYSCALL_GETPEERNAME;
	case __NR_getpgid: return IR0_SYSCALL_GETPGID;
	case __NR_getpid: return IR0_SYSCALL_GETPID;
	case __NR_getppid: return IR0_SYSCALL_GETPPID;
	case __NR_getpriority: return IR0_SYSCALL_GETPRIORITY;
	case __NR_getrandom: return IR0_SYSCALL_GETRANDOM;
	case __NR_getresgid: return IR0_SYSCALL_GETRESGID;
	case __NR_getresuid: return IR0_SYSCALL_GETRESUID;
	case __NR_getrlimit: return IR0_SYSCALL_GETRLIMIT;
	case __NR_getsid: return IR0_SYSCALL_GETSID;
	case __NR_getsockname: return IR0_SYSCALL_GETSOCKNAME;
	case __NR_getsockopt: return IR0_SYSCALL_GETSOCKOPT;
	case __NR_gettid: return IR0_SYSCALL_GETTID;
	case __NR_gettimeofday: return IR0_SYSCALL_GETTIMEOFDAY;
	case __NR_getuid: return IR0_SYSCALL_GETUID;
	case __NR_ioctl: return IR0_SYSCALL_IOCTL;
	case __NR_kexec_load: return IR0_SYSCALL_KEXEC_LOAD;
	case __NR_keymap_get: return IR0_SYSCALL_EXTENSION_KEYMAP_GET;
	case __NR_keymap_set: return IR0_SYSCALL_EXTENSION_KEYMAP_SET;
	case __NR_kill: return IR0_SYSCALL_KILL;
	case __NR_link: return IR0_SYSCALL_LINK;
	case __NR_listen: return IR0_SYSCALL_LISTEN;
	case __NR_lseek: return IR0_SYSCALL_LSEEK;
	case __NR_lstat: return IR0_SYSCALL_LSTAT;
	case __NR_memfd_create: return IR0_SYSCALL_MEMFD_CREATE;
	case __NR_mkdir: return IR0_SYSCALL_MKDIR;
	case __NR_mkdirat: return IR0_SYSCALL_MKDIRAT;
	case __NR_mknod: return IR0_SYSCALL_MKNOD;
	case __NR_mknodat: return IR0_SYSCALL_MKNODAT;
	case __NR_mmap: return IR0_SYSCALL_MMAP;
	case __NR_mount: return IR0_SYSCALL_MOUNT;
	case __NR_mprotect: return IR0_SYSCALL_MPROTECT;
	case __NR_munmap: return IR0_SYSCALL_MUNMAP;
	case __NR_nanosleep: return IR0_SYSCALL_NANOSLEEP;
	case __NR_newfstatat: return IR0_SYSCALL_NEWFSTATAT;
	case __NR_open: return IR0_SYSCALL_OPEN;
	case __NR_openat: return IR0_SYSCALL_OPENAT;
	case __NR_pause: return IR0_SYSCALL_PAUSE;
	case __NR_personality: return IR0_SYSCALL_PERSONALITY;
	case __NR_pipe: return IR0_SYSCALL_PIPE;
	case __NR_pipe2: return IR0_SYSCALL_PIPE2;
	case __NR_poll: return IR0_SYSCALL_POLL;
	case __NR_ppoll: return IR0_SYSCALL_PPOLL;
	case __NR_prctl: return IR0_SYSCALL_PRCTL;
	case __NR_prlimit64: return IR0_SYSCALL_PRLIMIT64;
	case __NR_pselect6: return IR0_SYSCALL_PSELECT6;
	case __NR_read: return IR0_SYSCALL_READ;
	case __NR_readlink: return IR0_SYSCALL_READLINK;
	case __NR_readlinkat: return IR0_SYSCALL_READLINKAT;
	case __NR_readv: return IR0_SYSCALL_READV;
	case __NR_reboot: return IR0_SYSCALL_REBOOT;
	case __NR_recvfrom: return IR0_SYSCALL_RECVFROM;
	case __NR_recvmsg: return IR0_SYSCALL_RECVMSG;
	case __NR_rename: return IR0_SYSCALL_RENAME;
	case __NR_renameat: return IR0_SYSCALL_RENAMEAT;
	case __NR_rmdir: return IR0_SYSCALL_RMDIR;
	case __NR_rt_sigaction: return IR0_SYSCALL_RT_SIGACTION;
	case __NR_rt_sigprocmask: return IR0_SYSCALL_RT_SIGPROCMASK;
	case __NR_rt_sigreturn: return IR0_SYSCALL_RT_SIGRETURN;
	case __NR_rt_sigsuspend: return IR0_SYSCALL_RT_SIGSUSPEND;
	case __NR_select: return IR0_SYSCALL_SELECT;
	case __NR_sendmsg: return IR0_SYSCALL_SENDMSG;
	case __NR_sendto: return IR0_SYSCALL_SENDTO;
	case __NR_set_robust_list: return IR0_SYSCALL_SET_ROBUST_LIST;
	case __NR_set_tid_address: return IR0_SYSCALL_SET_TID_ADDRESS;
	case __NR_setgid: return IR0_SYSCALL_SETGID;
	case __NR_setgroups: return IR0_SYSCALL_SETGROUPS;
	case __NR_setitimer: return IR0_SYSCALL_SETITIMER;
	case __NR_setpgid: return IR0_SYSCALL_SETPGID;
	case __NR_setpriority: return IR0_SYSCALL_SETPRIORITY;
	case __NR_setregid: return IR0_SYSCALL_SETREGID;
	case __NR_setresgid: return IR0_SYSCALL_SETRESGID;
	case __NR_setresuid: return IR0_SYSCALL_SETRESUID;
	case __NR_setreuid: return IR0_SYSCALL_SETREUID;
	case __NR_setsid: return IR0_SYSCALL_SETSID;
	case __NR_setsockopt: return IR0_SYSCALL_SETSOCKOPT;
	case __NR_setuid: return IR0_SYSCALL_SETUID;
	case __NR_shmat: return IR0_SYSCALL_SHMAT;
	case __NR_shmctl: return IR0_SYSCALL_SHMCTL;
	case __NR_shmdt: return IR0_SYSCALL_SHMDT;
	case __NR_shmget: return IR0_SYSCALL_SHMGET;
	case __NR_shutdown: return IR0_SYSCALL_SHUTDOWN;
	case __NR_socket: return IR0_SYSCALL_SOCKET;
	case __NR_socketpair: return IR0_SYSCALL_SOCKETPAIR;
	case __NR_stat: return IR0_SYSCALL_STAT;
	case __NR_statfs: return IR0_SYSCALL_STATFS;
	case __NR_symlink: return IR0_SYSCALL_SYMLINK;
	case __NR_symlinkat: return IR0_SYSCALL_SYMLINKAT;
	case __NR_sync: return IR0_SYSCALL_SYNC;
	case __NR_sysinfo: return IR0_SYSCALL_SYSINFO;
	case __NR_syslog: return IR0_SYSCALL_SYSLOG;
	case __NR_tgkill: return IR0_SYSCALL_TGKILL;
	case __NR_timerfd_create: return IR0_SYSCALL_TIMERFD_CREATE;
	case __NR_timerfd_gettime: return IR0_SYSCALL_TIMERFD_GETTIME;
	case __NR_timerfd_settime: return IR0_SYSCALL_TIMERFD_SETTIME;
	case __NR_tkill: return IR0_SYSCALL_TKILL;
	case __NR_truncate: return IR0_SYSCALL_TRUNCATE;
	case __NR_umask: return IR0_SYSCALL_UMASK;
	case __NR_umount2: return IR0_SYSCALL_UMOUNT2;
	case __NR_uname: return IR0_SYSCALL_UNAME;
	case __NR_unlink: return IR0_SYSCALL_UNLINK;
	case __NR_unlinkat: return IR0_SYSCALL_UNLINKAT;
	case __NR_utimensat: return IR0_SYSCALL_UTIMENSAT;
	case __NR_vfork: return IR0_SYSCALL_VFORK;
	case __NR_wait4: return IR0_SYSCALL_WAIT4;
	case __NR_write: return IR0_SYSCALL_WRITE;
	case __NR_writev: return IR0_SYSCALL_WRITEV;
	default: return IR0_SYSCALL_UNKNOWN;
	}
}
