#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate includes/generated/heart_src_blob.h from a fixed source list."""

from __future__ import annotations

import argparse
import pathlib
import sys


DEFAULT_FILES = [
    "includes/ir0/heart_src_probe.h",
    "includes/ir0/pseudo_fs.h",
    "includes/ir0/heartfs.h",
    "includes/ir0/version.h",
    "kernel/syscalls.c",
]


def c_escape(data: bytes) -> str:
    out = []
    for b in data:
        if b == ord("\\"):
            out.append("\\\\")
        elif b == ord('"'):
            out.append('\\"')
        elif 32 <= b < 127 and b != ord("?"):
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02x}")
    return "".join(out)


def emit(root: pathlib.Path, rels: list[str], out_path: pathlib.Path) -> None:
    files = []
    for rel in rels:
        path = root / rel
        if not path.is_file():
            raise SystemExit(f"missing source for /heart/src: {rel}")
        data = path.read_bytes()
        # Cap individual file to keep kernel image bounded.
        if len(data) > 65536:
            data = data[:65536]
        files.append((rel, data))

    lines = [
        "/* Auto-generated by scripts/gen_heart_src_blob.py — do not edit. */",
        "#pragma once",
        "#include <stddef.h>",
        "",
        "typedef struct heart_src_file {",
        "    const char *rel_path;",
        "    const unsigned char *data;",
        "    size_t size;",
        "} heart_src_file_t;",
        "",
    ]

    for i, (rel, data) in enumerate(files):
        lines.append(f"static const unsigned char heart_src_data_{i}[] = {{")
        chunk = []
        for j, b in enumerate(data):
            chunk.append(f"0x{b:02x}")
            if (j + 1) % 12 == 0:
                lines.append("    " + ", ".join(chunk) + ",")
                chunk = []
        if chunk:
            lines.append("    " + ", ".join(chunk) + ",")
        lines.append("};")
        lines.append("")

    lines.append(f"#define HEART_SRC_FILE_COUNT {len(files)}")
    lines.append("static const heart_src_file_t heart_src_files[HEART_SRC_FILE_COUNT] = {")
    for i, (rel, data) in enumerate(files):
        lines.append(
            f'    {{ "{rel}", heart_src_data_{i}, sizeof(heart_src_data_{i}) }},'
        )
    lines.append("};")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {out_path} ({len(files)} files)", file=sys.stderr)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=pathlib.Path, required=True)
    ap.add_argument("--out", type=pathlib.Path, required=True)
    ap.add_argument("files", nargs="*", default=DEFAULT_FILES)
    args = ap.parse_args()
    emit(args.root.resolve(), list(args.files) or DEFAULT_FILES, args.out.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
